version: "3.9"

services:
  fastapi:
    image: fastapi-todo
    container_name: fastapi_todo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/fastapi_db
      - SECRET_KEY=mysecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
